### ISSUE TITLE
How we use green as a status within steps

### ISSUE THREAD

**Issue by Tjkeel** [Tjkeel/Ethereum-Roadmap#4]
Right now we use green shading broadly: anything pre-Shanghai. Which in itself isn't perfect, but we're actually using it even more broadly. 

It is very clear when we use purple, blue, or red, as there are specific EIPs included in hard forks that we can point to. In the case of MaxEB, for example, we're marking it red because it will be included in Prague-Electra. However, a lot of the research and discussion relating to it happened over the course of years. But we've made the decision to mark it red, which I think is the correct one.

Uncompleted steps, wherein the discussion and research has taken place over several years, including during periods where Shanghai, Cancun, and Prague hardforks happen, but the upgrade is not slated to go live in a specific or hard fork (or can't) is less clear form a design perspective. Take 'Improve Cross Chain Rollup Standards" as an example. We're currently shading it green because Vitalik did in his diagram. But he means something different with his green shade.

I propose we use a different color in these scenarios. Essentially we want to distinguish between upgrades that went live before Shanghai (green), and ongoing research that has made progress during the course of Ethereum's life. I don't think these should be green. These are more akin to steps like "Full Rollup Scaling," which are shaded black, and correctly signify that their progress is not specific to any particular hard fork. We could simply follow this and have many more steps shaded black to match.

Another option would be to use multiple colors, and estimate the research progress that has been made during the period in which a hard fork was being worked on. I don't love this solution since we're using purple, blue, and red to signify inclusion in a hard fork. This DOES make sense for certain steps, like "Increase Validator Count" as EIPs were discretely included in the various hard forks to justify multiple colors.

To that end, I'm suggesting we differentiate between discrete and continuous progress. 

- Discrete -> Colors
- Continuous -> greyscale shading of some kind

Posting here for discussion, since it's not obvious which path we should take.

**Comment by Tjkeel** [comment]
I may not have explained this well. I could also be overthinking it, and any changes could cause more harm than good.

**Comment by GitWave22** [comment]
Interesting/good point, glad you brought that up.

> To that end, I'm suggesting we differentiate between discrete and continuous progress.
> 
> * Discrete -> Colors
> * Continuous -> greyscale shading of some kind

I think this would be a good solution and probably the best. 

There might be scope for "Continuous" to have a flashing element to them to indicate progress made between the last hardfork and the next planed hardfork (I want to optimize for showing progress) - I would be happy to add that functionality if you think its a good idea if you would be happy to input the figures.

**Comment by Tjkeel** [comment]
I'm hesitant to do this since it's a lot of work, but the more I think about it, the more it seems like we should just change the pre-shanghai color schema throughout the entire site to a new and different color, that way we can utilize the green shade to signify continuous progress.

**Comment by Tjkeel** [comment]
It's been a design flaw from the start. Since I've used green for pre-Shanghai upgrades, I haven't been able to use green anywhere else, which is an important color to signify "positive" or "yes" or "progress". It hadn't been a big issue until now, but now it is.

**Comment by GitWave22** [comment]
If we do use green for progress could it be a different pallet than the rest of the progress bar? The good thing about black is that it is easily distinguished as being different/seperate from the hardforks. Green is a more positive color though and is what was used on the original - I am actually ok with either green or black maaybe leaning towards black personally...

...

Another option that would be a lot of work and involve estimating progress between hardforks would be to have 2 pallets: 

Discrete - current pastel colors

Progress - Same pallet but lighter maybe transparent looking (transparency is used for red flash so we would have to emulate transparency) 

For me this would be the most functional for the users perspective but would be a lot of work including "guess" work - If things go to plan the guess work would be the starting point and the researchers and devs would alter it.
