### ISSUE TITLE
Diagram countdown animation (and pause/play option?) - post launch

### ISSUE THREAD

**Issue by GitWave22** [Tjkeel/Ethereum-Roadmap#7]
(this can be done post launch)

I think it would be cool to add something like this to the description boxes to indicate them moving to the next step
![image](https://github.com/Tjkeel/Ethereum-Roadmap/assets/135379882/60676fb3-61f3-4ec5-95e4-544a10e5321b)

If we incorporated a pause button in the middle there could be scope to reduce the time it takes to skip to the next step (slightly)  

Example code for timer - https://stackoverflow.com/questions/69481222/simple-countdown-circle-animation-with-pure-css

**Comment by Tjkeel** [comment]
Is there currently a long enough pause in between for this to be relevant? Doesn't seem like so on my machine at least
